name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python deps
        run: |
          python -m pip install -r backend/requirements.txt pytest
      - name: Pytest
        run: pytest
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Node deps
        run: |
          cd frontend && npm ci
      - name: Lint
        run: |
          cd frontend && npm run lint
      - name: Docker build
        run: docker compose build
